sudo: required
dist: trusty
language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
script: sbt clean coverage test
after_success: 
  - sbt coveralls
  - src/bin/publish_snapshot.sh
deploy:
  provider: script
  script: src/bin/publish_release.sh
  on:
    tags: true
